### ISSUE TITLE
Scaffold project using dext create

### ISSUE THREAD

**Issue by lucacasonato** [lucacasonato/dext.ts#6]
There should be a `dext create` command to scaffold a new project. This should create a `pages/` directory with a index page and a dynamic page, and the `tsconfig.json` file.

**Comment by bartlomieju** [comment]
I'll look into this one 🙃  what dynamic page should be created?

**Comment by lucacasonato** [comment]
Maybe just the one from the example? Something that just renders one of the path segments in the output.
