### ISSUE TITLE
Error on install on 1.7.0

### ISSUE THREAD

**Issue by RoXuS** [lucacasonato/dext.ts#60]
Hey,

thx for your project!

I get this error on check after install:
![image](https://user-images.githubusercontent.com/3296671/105827559-6fdd4b80-5fc2-11eb-9b6c-1cd5f36562ba.png)

**Comment by RoXuS** [comment]
probably this: https://github.com/denoland/deno/discussions/8800 ...

**Comment by RoXuS** [comment]
yeah on 1.6.3 it's ok.

**Comment by bartlomieju** [comment]
This is a problem with `dext` module which needs to be updated, not Deno itself, as you pointed out it because of #8800. 

CC @lucacasonato

**Comment by lucacasonato** [comment]
Please use dext@0.10.2

**Comment by RoXuS** [comment]
work as expected, thx!
