### ISSUE TITLE
Consider switching to /x/drollup

### ISSUE THREAD

**Issue by kt3k** [lucacasonato/dext.ts#65]
`drollup` (deno-rollup https://github.com/cmorten/deno-rollup) looks more maintained than denopack (It is tested with 1.7.4). It seems supporting import map (It has [import map plugin](https://github.com/cmorten/deno-rollup/tree/main/plugins/importmap)). With import map like `{"imports":{"@/", "./"}}` we can avoid excessively consecutive '../../' in application source. (The path like `"../../../components/blah"` can be written like `"@/components/blah"`

**Comment by lucacasonato** [comment]
Superseded by #75
